version: "3.9"
services:
  mysql_projeto:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3307:3306
  adminer_projeto:
    image: adminer
    restart: always
    ports:
      - 8081:8080
